#ifndef __SPELL_ELEMENTS_H__
#define __SPELL_ELEMENTS_H__

enum element_type {
    ELEMENT_TYPE_NONE = 0,
    ELEMENT_TYPE_FIRE = 1,
    ELEMENT_TYPE_ICE = 2,
    ELEMENT_TYPE_LIGHTNING = 3,
    ELEMENT_TYPE_WATER = 4,
    ELEMENT_TYPE_AIR = 5,
    ELEMENT_TYPE_LIFE = 6,
};

#endif