
global has_entered_fire_trials: bool;

func main()
    if has_entered_fire_trials then
        return;
    end

    pause;

    say "ready";
    
    delay 5.0;

    fade FADE_COLOR_NONE, 1;

    interact_with_location INTERACTION_MOVE, NPC_TYPE_PLAYER, "enter_run_target";
    npc_set_speed NPC_TYPE_PLAYER, 3.65;

    show_title "FIRE TRIALS";

    npc_wait NPC_TYPE_PLAYER;
    interact_with_location INTERACTION_LOOK, NPC_TYPE_PLAYER, "temple";
    cam_wait;
    cam_return;

    delay 1.0;
    
    comm_stone_start;

    say "
        Good, you made it

        Not many people have entered the trials since the genesis

        You may need to clear some overgrowth with your flame sword
    ";

    comm_stone_end;

    unpause;

    has_entered_fire_trials = true;
end