
global has_entered_fire_trials: bool;

func main()
    if has_entered_fire_trials then
        return;
    end

    pause;

    fade FADE_COLOR_NONE, 1;

    cam_animate "enter";

    interact_with_location INTERACTION_MOVE, NPC_TYPE_PLAYER, "enter_run_target";
    npc_set_speed NPC_TYPE_PLAYER, 0.65;

    delay 15;
    show_title "FIRE TRIALS";

    npc_wait NPC_TYPE_PLAYER;
    interact_with_location INTERACTION_LOOK, NPC_TYPE_PLAYER, "temple";
    cam_wait;
    cam_return;

    delay 1.0;
    
    comm_stone_start;

    say "
        Good, you made it

        Not many people have entered the trials since the genesis

        You may need to clear some overgrowth with your flame sword

        To cast spells hold Z then use the C buttons to enter your spell

        You only have a basic flame attack which is C right.

        Try casting that now.
    ";

    comm_stone_end;

    cam_behind_player;
    cam_wait;

    unpause;

    tutorial TUTORIAL_MENU_CREATE_FIRE;

    delay 4.0;

    pause;

    comm_stone_start;

    say "
        Good, now keep your wits about you.

        This place has been overrun with monsters since the genesis.

        Good luck.
    ";
    
    
    comm_stone_end;
    
    cam_behind_player;
    cam_wait;
    
    unpause;

    has_entered_fire_trials = true;
end