
func add(a: i32, b: i32): i32
    return a + b;
end

func test_return(): i32
    return 5;
end

func test_call_add(): i32
    return add(3, 5);
end

func multi_return(): i32, i32
    return 2, 3;
end

func local_swap(): i32, i32
    local a: i32 = 3;
    local b: i32 = 5;

    a, b = b, a;

    return a, b;
end

func unpack_fn(): i32
    local a: i32;
    local b: i32;

    a, b = multi_return();

    return a + b;
end

func built_in_call()
    show_boss_health "Name", 0;
end

func template_strings(): str
    local value: i32 = 123;
    return "this is {value} a test";
end

func main()
    local local_a: i32 = 20 + 30;
    local local_b: i32 = local_a * local_a;
end