
scene spin_torch_0: bool;
scene spin_torch_1: bool;
scene spin_torch_2: bool;
scene spin_torch_3: bool;
scene spin_torch_solved: bool;

scene crossing_jelly_0_died: bool;
scene crossing_jelly_1_died: bool;
scene crossing_jelly_2_died: bool;
scene crossing_jelly_all_died: bool;

scene crossing_door_open: bool;

scene elevator_active: bool;

scene basement_entrance_solved: bool;
scene basement_entrance_door_open: bool;
scene basement_entrance_drop_ball: bool;